//! Module: report - HTML report generation for scan results and optimizations

pub fn generate_html_report(title: &str, sections: &[(&str, &str)]) -> String {
    let mut html = format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #1a1a2e; color: #e0e0e0; }}
h1 {{ color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 10px; }}
h2 {{ color: #7b68ee; }}
.section {{ background: #16213e; border-radius: 8px; padding: 16px; margin: 16px 0; }}
.critical {{ border-left: 4px solid #ff4444; }}
.warning {{ border-left: 4px solid #ffaa00; }}
.ok {{ border-left: 4px solid #00cc66; }}
.footer {{ text-align: center; color: #666; margin-top: 40px; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>🔧 {title}</h1>
"#);
    for (heading, content) in sections {
        html.push_str(&format!(
            "<div class=\"section\"><h2>{heading}</h2><p>{content}</p></div>\n"
        ));
    }
    html.push_str("<div class=\"footer\">Generated by Cove Windows Optimizer</div>\n</body></html>");
    html
}
