import { invoke as tauriInvoke } from "@tauri-apps/api/core";

const IS_TAURI = "__TAURI__" in window || "__TAURI_INTERNALS__" in window;

// ---------------------------------------------------------------------------
// Mock data for browser development
// ---------------------------------------------------------------------------

const MOCKS: Record<string, unknown> = {
  get_system_info: {
    hostname: "DEV-PC",
    os: "linux",
    platform: "linux (dev mode)",
  },

  // ── Health ───────────────────────────────────────────────────────────
  get_health_report: {
    score: 72,
    findings: [
      {
        id: "disk.free_space",
        severity: "Warning",
        title: "System Drive Free Space",
        detail: "45.0 GB free of 500.0 GB (9.0%)",
        metric: { Percent: 9.0 },
        remediation: "Run Disk Cleanup to free space on the system drive",
      },
      {
        id: "ram.available",
        severity: "Ok",
        title: "Available RAM",
        detail: "8.5 GB available of 16.0 GB (53.1%)",
        metric: { Percent: 53.1 },
        remediation: null,
      },
      {
        id: "cpu.temp",
        severity: "Ok",
        title: "CPU Temperature",
        detail: "62 C - within normal operating range",
        metric: { Integer: 62 },
        remediation: null,
      },
      {
        id: "smart.status",
        severity: "Ok",
        title: "SMART Disk Health",
        detail: "All drives report healthy SMART status",
        metric: null,
        remediation: null,
      },
      {
        id: "battery.health",
        severity: "Warning",
        title: "Battery Wear Level",
        detail: "Design capacity 56,000 mWh, current full-charge 41,200 mWh (73.6%)",
        metric: { Percent: 73.6 },
        remediation: "Battery degradation is normal over time. Consider replacement below 50%.",
      },
      {
        id: "uptime",
        severity: "Info",
        title: "System Uptime",
        detail: "4 days, 7 hours - reboot recommended weekly",
        metric: { Integer: 370800 },
        remediation: "Restart the computer to clear stale resources",
      },
    ],
  },

  // ── Visual Tweaks ────────────────────────────────────────────────────
  get_visual_tweaks: [
    {
      id: "visual.transparency",
      name: "Disable Transparency",
      description: "Turn off window transparency effects to reduce GPU load",
      category: "Visual Effects",
      safety_tier: "Green",
      current_value: "1",
      optimized_value: "0",
      registry_path: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",
      registry_name: "EnableTransparency",
    },
    {
      id: "visual.animations",
      name: "Disable Minimize/Maximize Animations",
      description: "Remove window animation effects for snappier feel",
      category: "Visual Effects",
      safety_tier: "Green",
      current_value: "1",
      optimized_value: "0",
      registry_path: "HKCU\\Control Panel\\Desktop\\WindowMetrics",
      registry_name: "MinAnimate",
    },
    {
      id: "visual.taskbar_anim",
      name: "Disable Taskbar Animations",
      description: "Stop taskbar button animations",
      category: "Visual Effects",
      safety_tier: "Green",
      current_value: "1",
      optimized_value: "0",
      registry_path: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
      registry_name: "TaskbarAnimations",
    },
    {
      id: "visual.peek",
      name: "Disable Aero Peek",
      description: "Turn off desktop peek on taskbar hover",
      category: "Visual Effects",
      safety_tier: "Green",
      current_value: "1",
      optimized_value: "0",
      registry_path: "HKCU\\Software\\Microsoft\\Windows\\DWM",
      registry_name: "EnableAeroPeek",
    },
    {
      id: "visual.shadows",
      name: "Disable Icon Shadows",
      description: "Remove text shadows under desktop icons",
      category: "Visual Effects",
      safety_tier: "Green",
      current_value: "1",
      optimized_value: "0",
      registry_path: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
      registry_name: "ListviewShadow",
    },
    {
      id: "visual.smooth_scroll",
      name: "Disable Smooth Scrolling",
      description: "Turn off smooth scrolling in lists",
      category: "Visual Effects",
      safety_tier: "Green",
      current_value: "1",
      optimized_value: "0",
      registry_path: "HKCU\\Control Panel\\Desktop",
      registry_name: "SmoothScroll",
    },
  ],

  // ── Privacy Tweaks ───────────────────────────────────────────────────
  get_privacy_tweaks: [
    // Basic tier
    {
      id: "priv.advertising_id",
      name: "Disable Advertising ID",
      description: "Prevent apps from using your advertising ID for targeted ads",
      tier: "basic",
      safety: "Green",
      enabled: true,
      warning: null,
    },
    {
      id: "priv.tailored_experiences",
      name: "Disable Tailored Experiences",
      description: "Stop Microsoft from using diagnostic data to personalize tips and ads",
      tier: "basic",
      safety: "Green",
      enabled: true,
      warning: null,
    },
    {
      id: "priv.suggested_content",
      name: "Disable Suggested Content in Settings",
      description: "Remove Microsoft app suggestions in Settings",
      tier: "basic",
      safety: "Green",
      enabled: true,
      warning: null,
    },
    {
      id: "priv.start_suggestions",
      name: "Disable Start Menu Suggestions",
      description: "Remove app install suggestions from Start menu",
      tier: "basic",
      safety: "Green",
      enabled: true,
      warning: null,
    },
    // Standard tier
    {
      id: "priv.telemetry_basic",
      name: "Set Telemetry to Required Only",
      description: "Reduce Windows diagnostic data to the minimum required level",
      tier: "standard",
      safety: "Yellow",
      enabled: true,
      warning: "May affect personalized troubleshooting from Microsoft",
    },
    {
      id: "priv.activity_history",
      name: "Disable Activity History",
      description: "Stop Windows from collecting activity history for timeline",
      tier: "standard",
      safety: "Yellow",
      enabled: true,
      warning: null,
    },
    {
      id: "priv.location",
      name: "Disable Location Services",
      description: "Turn off system-wide location access",
      tier: "standard",
      safety: "Yellow",
      enabled: true,
      warning: "Weather and map apps will not auto-detect location",
    },
    {
      id: "priv.feedback_frequency",
      name: "Disable Feedback Prompts",
      description: "Stop Windows from asking for feedback",
      tier: "standard",
      safety: "Green",
      enabled: true,
      warning: null,
    },
    // Advanced tier
    {
      id: "priv.connected_experiences",
      name: "Disable Connected Experiences",
      description: "Turn off cloud-powered features in Office and Windows",
      tier: "advanced",
      safety: "Red",
      enabled: true,
      warning: "Some Office cloud features will stop working",
    },
    {
      id: "priv.cortana",
      name: "Disable Cortana",
      description: "Completely disable the Cortana assistant",
      tier: "advanced",
      safety: "Red",
      enabled: true,
      warning: "Voice assistant will be fully disabled",
    },
    {
      id: "priv.web_search",
      name: "Disable Web Search in Start",
      description: "Remove Bing web results from Start menu search",
      tier: "advanced",
      safety: "Yellow",
      enabled: true,
      warning: null,
    },
  ],

  // ── Services ─────────────────────────────────────────────────────────
  get_services_tweaks: {
    profiles: [
      {
        id: "conservative",
        name: "Conservative",
        description: "Disable only clearly unnecessary services",
      },
      {
        id: "advanced",
        name: "Advanced",
        description: "Disable more services for maximum performance (review carefully)",
      },
    ],
    services: [
      {
        name: "SysMain",
        display_name: "SysMain (Superfetch)",
        description: "Preloads frequently used apps into memory. Unnecessary on SSD.",
        current_state: "Running",
        current_start_type: "Automatic",
        target_start_type: "Disabled",
        profile: "conservative",
        safety: "Yellow",
      },
      {
        name: "DiagTrack",
        display_name: "Connected User Experiences and Telemetry",
        description: "Collects and sends diagnostic data to Microsoft.",
        current_state: "Running",
        current_start_type: "Automatic",
        target_start_type: "Disabled",
        profile: "conservative",
        safety: "Green",
      },
      {
        name: "WSearch",
        display_name: "Windows Search",
        description: "Content indexing and property caching for file search.",
        current_state: "Running",
        current_start_type: "Automatic (Delayed)",
        target_start_type: "Disabled",
        profile: "advanced",
        safety: "Yellow",
      },
      {
        name: "Fax",
        display_name: "Fax",
        description: "Enables sending and receiving faxes.",
        current_state: "Stopped",
        current_start_type: "Manual",
        target_start_type: "Disabled",
        profile: "conservative",
        safety: "Green",
      },
      {
        name: "MapsBroker",
        display_name: "Downloaded Maps Manager",
        description: "Application access to downloaded maps.",
        current_state: "Stopped",
        current_start_type: "Automatic (Delayed)",
        target_start_type: "Disabled",
        profile: "conservative",
        safety: "Green",
      },
      {
        name: "RetailDemo",
        display_name: "Retail Demo Service",
        description: "Controls retail demo mode for store display devices.",
        current_state: "Stopped",
        current_start_type: "Manual",
        target_start_type: "Disabled",
        profile: "conservative",
        safety: "Green",
      },
      {
        name: "WbioSrvc",
        display_name: "Windows Biometric Service",
        description: "Captures, compares, and stores biometric data.",
        current_state: "Running",
        current_start_type: "Automatic",
        target_start_type: "Disabled",
        profile: "advanced",
        safety: "Red",
      },
      {
        name: "TabletInputService",
        display_name: "Touch Keyboard and Handwriting",
        description: "Enables touch keyboard and handwriting pen functionality.",
        current_state: "Running",
        current_start_type: "Automatic",
        target_start_type: "Disabled",
        profile: "advanced",
        safety: "Yellow",
      },
    ],
  },

  // ── Startup Items ────────────────────────────────────────────────────
  get_startup_items: [
    {
      name: "Microsoft OneDrive",
      publisher: "Microsoft Corporation",
      command: "C:\\Users\\User\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe /background",
      location: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "High",
    },
    {
      name: "Discord",
      publisher: "Discord Inc.",
      command: "C:\\Users\\User\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe",
      location: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "High",
    },
    {
      name: "Spotify",
      publisher: "Spotify AB",
      command: "C:\\Users\\User\\AppData\\Roaming\\Spotify\\Spotify.exe /minimized",
      location: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "Medium",
    },
    {
      name: "Steam Client Bootstrapper",
      publisher: "Valve Corporation",
      command: "\"C:\\Program Files (x86)\\Steam\\steam.exe\" /silent",
      location: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "High",
    },
    {
      name: "Microsoft Teams",
      publisher: "Microsoft Corporation",
      command: "C:\\Users\\User\\AppData\\Local\\Microsoft\\Teams\\Update.exe --processStart Teams.exe",
      location: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: false,
      impact: "High",
    },
    {
      name: "Realtek HD Audio Manager",
      publisher: "Realtek Semiconductor",
      command: "\"C:\\Program Files\\Realtek\\Audio\\HDA\\RtkNGUI64.exe\" -s",
      location: "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "Low",
    },
    {
      name: "Windows Security Notification",
      publisher: "Microsoft Corporation",
      command: "%ProgramFiles%\\Windows Defender\\MSASCuiL.exe",
      location: "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "Low",
    },
    {
      name: "NVIDIA GeForce Experience",
      publisher: "NVIDIA Corporation",
      command: "\"C:\\Program Files\\NVIDIA Corporation\\NVIDIA GeForce Experience\\NVIDIA Share.exe\"",
      location: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      enabled: true,
      impact: "Medium",
    },
  ],

  // ── Cleanup Targets ──────────────────────────────────────────────────
  get_cleanup_targets: [
    {
      id: "temp_user",
      name: "User Temp Files",
      description: "Temporary files in %TEMP%",
      path: "C:\\Users\\User\\AppData\\Local\\Temp",
      size_bytes: 2_147_483_648,
      file_count: 12480,
      safe: true,
    },
    {
      id: "temp_windows",
      name: "Windows Temp Files",
      description: "System temporary files in C:\\Windows\\Temp",
      path: "C:\\Windows\\Temp",
      size_bytes: 536_870_912,
      file_count: 3210,
      safe: true,
    },
    {
      id: "prefetch",
      name: "Prefetch Cache",
      description: "Application prefetch data - rebuilds automatically",
      path: "C:\\Windows\\Prefetch",
      size_bytes: 134_217_728,
      file_count: 284,
      safe: true,
    },
    {
      id: "thumbnails",
      name: "Thumbnail Cache",
      description: "Explorer thumbnail database files",
      path: "C:\\Users\\User\\AppData\\Local\\Microsoft\\Windows\\Explorer",
      size_bytes: 314_572_800,
      file_count: 12,
      safe: true,
    },
    {
      id: "recycle_bin",
      name: "Recycle Bin",
      description: "Deleted files waiting for permanent removal",
      path: "$Recycle.Bin",
      size_bytes: 1_073_741_824,
      file_count: 89,
      safe: true,
    },
    {
      id: "windows_update",
      name: "Windows Update Cleanup",
      description: "Previous Windows Update downloaded files",
      path: "C:\\Windows\\SoftwareDistribution\\Download",
      size_bytes: 3_221_225_472,
      file_count: 1540,
      safe: true,
    },
    {
      id: "crash_dumps",
      name: "Crash Dump Files",
      description: "System and user crash memory dumps",
      path: "C:\\Windows\\Minidump",
      size_bytes: 268_435_456,
      file_count: 5,
      safe: true,
    },
    {
      id: "delivery_opt",
      name: "Delivery Optimization Files",
      description: "Windows Update delivery cache for LAN sharing",
      path: "C:\\Windows\\ServiceProfiles\\NetworkService\\AppData\\Local\\Microsoft\\Windows\\DeliveryOptimization",
      size_bytes: 524_288_000,
      file_count: 48,
      safe: true,
    },
  ],

  // ── Power ────────────────────────────────────────────────────────────
  get_power_info: {
    active_plan: {
      guid: "381b4222-f694-41f0-9685-ff5bb260df2e",
      name: "Balanced",
    },
    plans: [
      { guid: "381b4222-f694-41f0-9685-ff5bb260df2e", name: "Balanced" },
      { guid: "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c", name: "High Performance" },
      { guid: "a1841308-3541-4fab-bc81-f71556f20b4a", name: "Power Saver" },
    ],
    settings: {
      display_off_ac_minutes: 15,
      display_off_dc_minutes: 5,
      sleep_ac_minutes: 30,
      sleep_dc_minutes: 15,
      hdd_off_ac_minutes: 20,
      hdd_off_dc_minutes: 10,
      hibernate_enabled: true,
    },
    battery: {
      present: true,
      charge_percent: 68,
      charging: true,
      estimated_minutes: 142,
    },
  },

  // ── Event Log ────────────────────────────────────────────────────────
  get_event_log_summary: {
    system: {
      total: 4280,
      critical: 2,
      error: 18,
      warning: 142,
      events: [
        {
          id: 41,
          source: "Kernel-Power",
          level: "Critical",
          message: "The system has rebooted without cleanly shutting down first.",
          time: "2026-06-08T02:14:00Z",
          count: 2,
        },
        {
          id: 7034,
          source: "Service Control Manager",
          level: "Error",
          message: "The Windows Audio service terminated unexpectedly. It has done this 3 time(s).",
          time: "2026-06-07T18:30:00Z",
          count: 3,
        },
        {
          id: 10016,
          source: "DistributedCOM",
          level: "Error",
          message: "The application-specific permission settings do not grant Local Activation permission for the COM Server application.",
          time: "2026-06-07T15:22:00Z",
          count: 12,
        },
        {
          id: 134,
          source: "Time-Service",
          level: "Warning",
          message: "NtpClient was unable to set a domain peer to use as a time source because of DNS resolution failure.",
          time: "2026-06-08T06:00:00Z",
          count: 8,
        },
        {
          id: 1014,
          source: "DNS Client Events",
          level: "Warning",
          message: "Name resolution for the name wpad timed out after none of the configured DNS servers responded.",
          time: "2026-06-08T05:45:00Z",
          count: 24,
        },
      ],
    },
    application: {
      total: 6150,
      critical: 0,
      error: 8,
      warning: 64,
      events: [
        {
          id: 1000,
          source: "Application Error",
          level: "Error",
          message: "Faulting application name: explorer.exe, version: 10.0.22631.2506",
          time: "2026-06-07T14:08:00Z",
          count: 1,
        },
        {
          id: 1002,
          source: "Application Hang",
          level: "Error",
          message: "The program msedge.exe stopped interacting with Windows and was closed.",
          time: "2026-06-06T22:15:00Z",
          count: 2,
        },
        {
          id: 1026,
          source: ".NET Runtime",
          level: "Error",
          message: "Application: Teams.exe. Framework Version: v4.0.30319. Unhandled exception.",
          time: "2026-06-06T16:42:00Z",
          count: 1,
        },
        {
          id: 11724,
          source: "MsiInstaller",
          level: "Warning",
          message: "Product: Visual C++ 2019 Redistributable -- Configuration completed successfully.",
          time: "2026-06-05T10:30:00Z",
          count: 3,
        },
      ],
    },
  },

  // ── BSOD ─────────────────────────────────────────────────────────────
  get_bsod_dumps: [
    {
      filename: "060726-12500-01.dmp",
      timestamp: "2026-06-07T02:14:22Z",
      bug_check_code: "0x0000009F",
      bug_check_name: "DRIVER_POWER_STATE_FAILURE",
      faulting_module: "ntoskrnl.exe",
      faulting_driver: "usbhub3.sys",
      detail: "A driver has failed to complete a power IRP within a specific time period.",
      recommendation: "Update USB hub drivers. Check for BIOS/firmware updates. Disconnect external USB devices to isolate.",
    },
    {
      filename: "060526-18200-01.dmp",
      timestamp: "2026-06-05T14:38:10Z",
      bug_check_code: "0x000000D1",
      bug_check_name: "DRIVER_IRQL_NOT_LESS_OR_EQUAL",
      faulting_module: "ndis.sys",
      faulting_driver: "rt640x64.sys",
      detail: "A kernel-mode driver attempted to access pageable memory at too high an IRQL.",
      recommendation: "Update Realtek network adapter driver to the latest version from the manufacturer.",
    },
    {
      filename: "052826-09100-01.dmp",
      timestamp: "2026-05-28T07:12:45Z",
      bug_check_code: "0x0000007E",
      bug_check_name: "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED",
      faulting_module: "win32kfull.sys",
      faulting_driver: "nvlddmkm.sys",
      detail: "A system thread generated an exception which the error handler did not catch.",
      recommendation: "Update NVIDIA display driver. Consider rolling back to a previous stable version if crashes persist.",
    },
  ],

  // ── Drivers ──────────────────────────────────────────────────────────
  get_driver_audit: {
    total: 142,
    unsigned: 3,
    outdated: 5,
    problematic: [
      {
        name: "Realtek PCIe GbE Family Controller",
        driver_file: "rt640x64.sys",
        version: "10.45.928.2020",
        date: "2022-03-15",
        signed: true,
        status: "outdated",
        detail: "Driver is 4 years old. Newer version 10.62.301.2024 available.",
      },
      {
        name: "NVIDIA GeForce RTX 3070",
        driver_file: "nvlddmkm.sys",
        version: "537.70",
        date: "2024-01-10",
        signed: true,
        status: "outdated",
        detail: "Associated with BSOD 0x0000007E on 2026-05-28. Update recommended.",
      },
      {
        name: "VirtualBox Host-Only Ethernet Adapter",
        driver_file: "VBoxNetAdp6.sys",
        version: "6.1.40",
        date: "2022-10-20",
        signed: false,
        status: "unsigned",
        detail: "Third-party unsigned driver. May cause issues with Secure Boot.",
      },
      {
        name: "Razer Synapse Driver",
        driver_file: "rzdevmgmt.sys",
        version: "1.0.18.2",
        date: "2023-06-14",
        signed: false,
        status: "unsigned",
        detail: "Unsigned kernel driver. Common source of stability issues.",
      },
      {
        name: "WinPcap Packet Driver",
        driver_file: "npf.sys",
        version: "4.1.3.0",
        date: "2019-11-08",
        signed: false,
        status: "unsigned",
        detail: "Legacy packet capture driver. Consider replacing with npcap.",
      },
    ],
    healthy: [
      {
        name: "Intel(R) UHD Graphics 770",
        driver_file: "igdkmd64.sys",
        version: "31.0.101.5186",
        date: "2025-12-01",
        signed: true,
        status: "ok",
      },
      {
        name: "High Definition Audio Device",
        driver_file: "hdaudio.sys",
        version: "10.0.22621.1",
        date: "2024-06-21",
        signed: true,
        status: "ok",
      },
      {
        name: "Microsoft ACPI-Compliant System",
        driver_file: "acpi.sys",
        version: "10.0.22621.3155",
        date: "2024-08-14",
        signed: true,
        status: "ok",
      },
    ],
  },

  // ── Network Diagnostics ──────────────────────────────────────────────
  get_network_diagnostics: {
    adapters: [
      {
        name: "Ethernet",
        type: "Ethernet",
        mac: "A4:BB:6D:0C:3E:91",
        ipv4: "192.168.1.105",
        ipv6: "fe80::a6bb:6dff:fe0c:3e91",
        gateway: "192.168.1.1",
        dns: ["1.1.1.1", "8.8.8.8"],
        speed: "1 Gbps",
        status: "Connected",
      },
      {
        name: "Wi-Fi",
        type: "WiFi",
        mac: "9C:2F:9D:B1:44:E2",
        ipv4: null,
        ipv6: null,
        gateway: null,
        dns: [],
        speed: null,
        status: "Disconnected",
      },
    ],
    tests: [
      {
        name: "DNS Resolution (1.1.1.1)",
        status: "pass",
        latency_ms: 12,
        detail: "Resolved google.com in 12ms",
      },
      {
        name: "DNS Resolution (8.8.8.8)",
        status: "pass",
        latency_ms: 18,
        detail: "Resolved google.com in 18ms",
      },
      {
        name: "Gateway Ping",
        status: "pass",
        latency_ms: 1,
        detail: "192.168.1.1 responded in 1ms",
      },
      {
        name: "Internet Connectivity",
        status: "pass",
        latency_ms: 22,
        detail: "Connected to microsoft.com in 22ms",
      },
      {
        name: "Packet Loss Test",
        status: "pass",
        latency_ms: null,
        detail: "0% packet loss over 20 pings",
      },
      {
        name: "IPv6 Connectivity",
        status: "warn",
        latency_ms: null,
        detail: "IPv6 not available on current network",
      },
    ],
    wifi: null,
  },

  // ── Windows Updates ──────────────────────────────────────────────────
  get_update_status: {
    last_check: "2026-06-08T04:00:00Z",
    last_install: "2026-06-03T02:15:00Z",
    reboot_required: false,
    pending_updates: [
      {
        title: "2026-06 Cumulative Update for Windows 11 (KB5039302)",
        kb: "KB5039302",
        severity: "Critical",
        size_bytes: 524_288_000,
        classification: "Security Updates",
      },
      {
        title: "2026-06 .NET 8.0.6 Security Update (KB5039293)",
        kb: "KB5039293",
        severity: "Important",
        size_bytes: 52_428_800,
        classification: "Security Updates",
      },
      {
        title: "Intel - System - 5/2026",
        kb: null,
        severity: "Optional",
        size_bytes: 15_728_640,
        classification: "Driver Updates",
      },
    ],
    component_store: {
      health: "Healthy",
      size_bytes: 8_589_934_592,
      last_cleanup: "2026-05-20T10:30:00Z",
      pending_cleanup_bytes: 1_073_741_824,
    },
  },

  // ── Change History ───────────────────────────────────────────────────
  get_change_history: [
    {
      id: 1,
      timestamp: "2026-06-08T10:30:00Z",
      module: "visual",
      description: "Applied: Disable Transparency",
      operation: "RegWrite",
      detail: "HKCU\\...\\Personalize\\EnableTransparency = 0",
      status: "committed",
      undone: false,
    },
    {
      id: 2,
      timestamp: "2026-06-08T10:30:01Z",
      module: "visual",
      description: "Applied: Disable Minimize/Maximize Animations",
      operation: "RegWrite",
      detail: "HKCU\\...\\WindowMetrics\\MinAnimate = 0",
      status: "committed",
      undone: false,
    },
    {
      id: 3,
      timestamp: "2026-06-08T10:30:02Z",
      module: "visual",
      description: "Applied: Disable Taskbar Animations",
      operation: "RegWrite",
      detail: "HKCU\\...\\Advanced\\TaskbarAnimations = 0",
      status: "committed",
      undone: false,
    },
    {
      id: 4,
      timestamp: "2026-06-07T16:45:00Z",
      module: "services",
      description: "Disabled: Connected User Experiences and Telemetry",
      operation: "ServiceStateChange",
      detail: "DiagTrack: Automatic -> Disabled",
      status: "committed",
      undone: true,
    },
    {
      id: 5,
      timestamp: "2026-06-07T16:45:01Z",
      module: "startup",
      description: "Disabled: Discord auto-start",
      operation: "TaskToggle",
      detail: "HKCU\\...\\Run\\Discord",
      status: "committed",
      undone: false,
    },
    {
      id: 6,
      timestamp: "2026-06-06T12:00:00Z",
      module: "cleanup",
      description: "Cleaned: User Temp Files",
      operation: "FileDelete",
      detail: "Removed 1,842 files (1.2 GB)",
      status: "committed",
      undone: false,
    },
    {
      id: 7,
      timestamp: "2026-06-06T12:00:01Z",
      module: "power",
      description: "Changed power plan to High Performance",
      operation: "PowerSchemeChange",
      detail: "Balanced -> High Performance",
      status: "failed",
      undone: false,
    },
  ],

  // ── Apply / Undo commands (return success) ───────────────────────────
  apply_tweak: { success: true },
  undo_tweak: { success: true },
  apply_batch: { success: true, applied: 6 },
  toggle_startup: { success: true },
  run_cleanup: { success: true, freed_bytes: 2_147_483_648 },
  set_power_plan: { success: true },
  apply_service_change: { success: true },
  undo_change: { success: true },
};

// ---------------------------------------------------------------------------
// Typed invoke wrapper
// ---------------------------------------------------------------------------

export async function invoke<T>(cmd: string, args?: Record<string, unknown>): Promise<T> {
  if (IS_TAURI) {
    return tauriInvoke<T>(cmd, args);
  }
  // Simulate a brief network delay
  await new Promise((r) => setTimeout(r, 120 + Math.random() * 200));
  if (cmd in MOCKS) {
    // Deep-clone to prevent mutation of mock data
    return JSON.parse(JSON.stringify(MOCKS[cmd])) as T;
  }
  console.warn(`[tauri-mock] No mock for command: ${cmd}`);
  return {} as T;
}
